version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3.8-management-alpine"
    environment:
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    ports:
      # RabbitMq instance
      - '5672:5672'
      #Webinterface
      - '15672:15672' 